
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DELL
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    private String getUserCode = "";
    private String getCode = "";
    private int max = 0;

    public void clear() {
        name.setText("");
        age.setText("0");
        mob.setText("");
        getName.setText("NAME");
        getAge.setText("0");
        getMobile.setText("");
        search.setText("");

    }

    public void update() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "2507");
            Statement st = con.createStatement();
            String Query = "select max(sn) from hospital_management_user_code;";
            ResultSet rs = st.executeQuery(Query);
            rs.next();
            int n = rs.getInt("max(sn)");
            n++;
            String pre = "0105SS22", suff = "";

            if (n < 10) {
                suff = "00";
            } else if (n < 100) {
                suff = "0";
            }
            getCode = pre + suff + n;
            max = n;
            userCode.setText(getCode);
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public admin() {
        initComponents();
        getMobile.setEditable(false);
        edit.setEnabled(false);
        update.setEnabled(false);
        search.setEnabled(true);
        update();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        userCode = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        age = new javax.swing.JTextField();
        mob = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        update = new javax.swing.JButton();
        getName = new javax.swing.JLabel();
        getAge = new javax.swing.JLabel();
        getMobile = new javax.swing.JTextField();
        search = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setForeground(new java.awt.Color(204, 153, 255));
        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 0, 22)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("USER ID : ");

        name.setBackground(new java.awt.Color(0, 51, 51));
        name.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 204));
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 2));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("NAME : ");

        userCode.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        userCode.setForeground(new java.awt.Color(255, 255, 204));
        userCode.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userCode.setText("0105SS22001");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("MOBILE : ");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("AGE : ");

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 255, 0));
        jButton1.setText("CREATE");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        age.setBackground(new java.awt.Color(0, 51, 51));
        age.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 204));
        age.setText("0");
        age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 2));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageKeyTyped(evt);
            }
        });

        mob.setBackground(new java.awt.Color(0, 51, 51));
        mob.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        mob.setForeground(new java.awt.Color(255, 255, 204));
        mob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 2));
        mob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mobKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(147, 147, 147)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(userCode, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(193, 193, 193)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(mob, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userCode, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(" CREATE NEW USER ", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("ENTER USER ID : ");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("AGE : ");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("MOBILE : ");

        edit.setBackground(new java.awt.Color(0, 0, 102));
        edit.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        edit.setForeground(new java.awt.Color(204, 204, 255));
        edit.setText("EDIT");
        edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204), 2));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(0, 0, 102));
        update.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        update.setForeground(new java.awt.Color(255, 204, 204));
        update.setText("UPDATE");
        update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        getName.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        getName.setForeground(new java.awt.Color(153, 255, 255));
        getName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getName.setText("NAME");

        getAge.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        getAge.setForeground(new java.awt.Color(153, 255, 255));
        getAge.setText("AGE");

        getMobile.setBackground(new java.awt.Color(0, 0, 51));
        getMobile.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        getMobile.setForeground(new java.awt.Color(153, 255, 255));
        getMobile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 2));
        getMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getMobileKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                getMobileKeyTyped(evt);
            }
        });

        search.setBackground(new java.awt.Color(0, 0, 51));
        search.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        search.setForeground(new java.awt.Color(153, 255, 255));
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 2));
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 51));
        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 153, 255));
        jButton4.setText("SEARCH");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 255), 2));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(getName, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(getMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(getAge, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(115, 115, 115)
                .addComponent(getName)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(getAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(getMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(" UPDATE USER DETAILS ", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 710, 620));

        logOut.setBackground(new java.awt.Color(255, 204, 204));
        logOut.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        logOut.setForeground(new java.awt.Color(255, 0, 0));
        logOut.setText("Log Out");
        logOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        getContentPane().add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1730, 0, 190, 50));

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 50)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 255, 255));
        jLabel24.setText("PRASH");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, -1, -1));

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 50)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("HOSPITAL");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 102));
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\OneDrive\\Documents\\NetBeansProjects\\Hospital_Management\\img\\admin.jpg")); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204), 2));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name_ = name.getText();
        int age_ = Integer.parseInt(age.getText());
        String mobile = mob.getText();
        if (mobile.length() < 10) {
            JOptionPane.showMessageDialog(null, "Plaese enter a VALID PHONE NUMBER!");
        } else {
            if ((name_ != null) && (age_ != 0)) {
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "2507");
                    Statement st = con.createStatement();
                    String Query = "insert into hospital_management_user_code values(" + max + ", '" + getCode + "', '" + name_ + "', " + age_ + ", '" + mobile + "', '');";
                    st.executeUpdate(Query);
                    JOptionPane.showMessageDialog(null, "Acoount " + getCode + " created successfully!");
                    update();
                    con.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "PLEASE FILL THE FORM PROPERLY!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "PLEASE FILL THE FORM PROPERLY!");
            }
        }
        System.out.println("" + getCode);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_ENTER) || (evt.getKeyCode() == KeyEvent.VK_DOWN)) {
            age.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            mob.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyPressed

    private void ageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_ENTER) || (evt.getKeyCode() == KeyEvent.VK_DOWN)) {
            mob.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            name.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ageKeyPressed

    private void mobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobKeyPressed
        boolean t;
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            t = true;
            if ((mob.getText().length() > 10) || (mob.getText().length() < 10)) {
                JOptionPane.showMessageDialog(null, "Please Enter a Valid Phone Number!");
                mob.setText("");
                t = false;
            }
            if (t == true) {
                name.requestFocus();
            } else {
                mob.requestFocus();
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            t = true;
            if ((mob.getText().length() > 10) || (mob.getText().length() < 10)) {
                JOptionPane.showMessageDialog(null, "Please Enter a Valid Phone Number!");
                mob.setText("");
                t = false;
            }
            if (t == true) {
                age.requestFocus();
            } else {
                mob.requestFocus();
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t = true;
            if ((mob.getText().length() > 10) || (mob.getText().length() < 10)) {
                JOptionPane.showMessageDialog(null, "Please Enter a Valid Phone Number!");
                mob.setText("");
                t = false;
            }
            if (t == true) {
                String name_ = name.getText();
                int age_ = Integer.parseInt(age.getText());
                String mobile = mob.getText();
                if (mobile.length() < 10) {
                    JOptionPane.showMessageDialog(null, "Plaese enter a VALID PHONE NUMBER!");
                } else {
                    if ((name_ != null) && (age_ != 0)) {
                        try {
                            Class.forName("com.mysql.jdbc.Driver");
                            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "2507");
                            Statement st = con.createStatement();
                            String Query = "insert into hospital_management_user_code values(" + max + ", '" + getCode + "', '" + name_ + "', " + age_ + ", '" + mobile + "', '');";
                            st.executeUpdate(Query);
                            JOptionPane.showMessageDialog(null, "Acoount " + getCode + " created successfully!");
                            update();
                            con.close();
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "PLEASE FILL THE FORM PROPERLY!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "PLEASE FILL THE FORM PROPERLY!");
                    }
                }
            } else {
                mob.requestFocus();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_mobKeyPressed

    private void ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyTyped
        char c = evt.getKeyChar();

        // TODO add your handling code here:
    }//GEN-LAST:event_ageKeyTyped

    private void mobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        String s = mob.getText();
        if (s.length() > 9) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_mobKeyTyped

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String code = search.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "2507");
            Statement st = con.createStatement();

            String Query = "select * from hospital_management_user_code where userCode = '" + code + "';";
            ResultSet rs = st.executeQuery(Query);
            rs.next();

            getName.setText(rs.getString("name"));
            getAge.setText("" + rs.getInt("age"));
            getMobile.setText(rs.getString("mobile"));
            getUserCode = code;
            edit.setEnabled(true);
            System.out.println("userCode : " + code);
            con.close();

        } catch (Exception e) {
            edit.setEnabled(false);
            JOptionPane.showMessageDialog(null, "INVALID USER CODE!");
            search.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        getMobile.setEditable(true);
        getMobile.requestFocus();
        update.setEnabled(true);
        edit.setEnabled(false);
        search.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        System.out.println("mob: " + getMobile.getText());
        if (getMobile.getText().length() < 10) {
            JOptionPane.showMessageDialog(null, "PLEASE ENTER A VALID PHONE NUMBER!");
            getMobile.requestFocus();
        } else {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "2507");
                Statement st = con.createStatement();
                String Query = "update hospital_management_user_code set mobile = '" + getMobile.getText() + "' where userCode = '" + getUserCode + "';";
                st.executeUpdate(Query);
                JOptionPane.showMessageDialog(null, "UPDATED SUCCESSFULLY!");
                getMobile.setEditable(false);
                search.setEnabled(true);
                search.requestFocus();
                edit.setEnabled(false);
                update.setEnabled(false);
                clear();
                con.close();
            } catch (Exception e) {
                System.out.println(e);
            }
        }

    }//GEN-LAST:event_updateActionPerformed

    private void getMobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_getMobileKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        String s = mob.getText();
        if (s.length() > 9) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_getMobileKeyTyped

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String code = search.getText();
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "2507");
                Statement st = con.createStatement();

                String Query = "select * from hospital_management_user_code where userCode = '" + code + "';";
                ResultSet rs = st.executeQuery(Query);
                rs.next();

                getName.setText(rs.getString("name"));
                getAge.setText("" + rs.getInt("age"));
                getMobile.setText(rs.getString("mobile"));
                getUserCode = code;
                edit.setEnabled(true);
                System.out.println("userCode : " + code);
                con.close();

            } catch (Exception e) {
                edit.setEnabled(false);
                JOptionPane.showMessageDialog(null, "INVALID USER CODE!");
                search.requestFocus();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_searchKeyPressed

    private void getMobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_getMobileKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("mob: " + getMobile.getText());
            if (getMobile.getText().length() < 10) {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER A VALID PHONE NUMBER!");
                getMobile.requestFocus();
            } else {
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "2507");
                    Statement st = con.createStatement();
                    String Query = "update hospital_management_user_code set mobile = '" + getMobile.getText() + "' where userCode = '" + getUserCode + "';";
                    st.executeUpdate(Query);
                    JOptionPane.showMessageDialog(null, "UPDATED SUCCESSFULLY!");
                    getMobile.setEditable(false);
                    search.setEnabled(true);
                    search.requestFocus();
                    edit.setEnabled(false);
                    update.setEnabled(false);
                    clear();
                    con.close();
                } catch (Exception e) {
                    System.out.println(e);
                }
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_getMobileKeyPressed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you want to LOG OUT?", "* * * ALERT * * *", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            new logIn().setVisible(true);
            new logIn().request();
            setVisible(false);
        }
    }//GEN-LAST:event_logOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JButton edit;
    private javax.swing.JLabel getAge;
    private javax.swing.JTextField getMobile;
    private javax.swing.JLabel getName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logOut;
    private javax.swing.JTextField mob;
    private javax.swing.JTextField name;
    private javax.swing.JTextField search;
    private javax.swing.JButton update;
    private javax.swing.JLabel userCode;
    // End of variables declaration//GEN-END:variables
}
