
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DELL
 */
public class logIn extends javax.swing.JFrame {

    /**
     * Creates new form logIn
     */
    public static String getLogInUserID = "";
    public static String getLogInPassword = "";

    public logIn() {
        initComponents();
        id.requestFocus();

    }

    public void request() {
        id.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        pwd = new javax.swing.JPasswordField();
        logIn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("LOGIN");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("userID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 510, -1, -1));

        id.setBackground(new java.awt.Color(255, 255, 204));
        id.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 380, -1));

        pwd.setBackground(new java.awt.Color(255, 255, 204));
        pwd.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdActionPerformed(evt);
            }
        });
        pwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdKeyPressed(evt);
            }
        });
        getContentPane().add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 550, 380, -1));

        logIn.setBackground(new java.awt.Color(204, 204, 255));
        logIn.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        logIn.setForeground(new java.awt.Color(0, 0, 204));
        logIn.setText("LOGIN");
        logIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInActionPerformed(evt);
            }
        });
        logIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                logInKeyPressed(evt);
            }
        });
        getContentPane().add(logIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 610, 410, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Forgot Password?");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 670, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("X");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 240, -1, 40));

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 50)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 204));
        jLabel24.setText("PRASH");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, -1, -1));

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 50)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("HOSPITAL");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logInBG.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you want to EXIT?", "* * * ALERT * * *", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInActionPerformed
        String admin = "@admin";
        String adminPwd = "admin@123";
        String userID = id.getText();
        String password = pwd.getText();
        String getID = "";
        String getPassword = "";
        if (userID.equals(admin) && password.equals(adminPwd)) {
            new admin().setVisible(true);
            setVisible(false);

        } else {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "2507");
                Statement st = con.createStatement();
                String Query = "select * from hospital_management_user where userID = '" + userID + "';";
                ResultSet rs = st.executeQuery(Query);
                rs.next();
                getID = rs.getString("userID");
                getPassword = rs.getString("password");
                getLogInUserID = getID;
                getLogInPassword = getPassword;
                if ((userID.equals(getID)) && (password.equals(getPassword))) {
                    getLogInUserID = getID;
                    getLogInPassword = getPassword;
                    new home().setVisible(true);
                    setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "INVALID USER_ID or PASSWORD !");
                    id.setText("");
                    pwd.setText("");
                    id.requestFocus();
                }
                con.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "INVALID USER_ID or PASSWORD !");
                id.setText("");
                pwd.setText("");
                id.requestFocus();
            }

        }
    }//GEN-LAST:event_logInActionPerformed

    private void logInKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_logInKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String userID = id.getText();
            String password = pwd.getText();
            String getID = "P0101";
            String getPassword = "123";
            if ((userID.equals(getID)) && (password.equals(getPassword))) {
                new home().setVisible(true);
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "INVALID USER_ID or PASSWORD !");
                id.setText("");
                pwd.setText("");
                id.requestFocus();
            }
        }
    }//GEN-LAST:event_logInKeyPressed

    private void pwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String admin = "@admin";
            String adminPwd = "admin@123";
            String userID = id.getText();
            String password = pwd.getText();
            String getID = "";
            String getPassword = "";
            if (userID.equals(admin) && password.equals(adminPwd)) {
                new admin().setVisible(true);
                setVisible(false);

            } else {
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "2507");
                    Statement st = con.createStatement();
                    String Query = "select * from hospital_management_user where userID = '" + userID + "';";
                    ResultSet rs = st.executeQuery(Query);
                    rs.next();
                    getID = rs.getString("userID");
                    getPassword = rs.getString("password");
                    getLogInUserID = getID;
                    getLogInPassword = getPassword;
                    if ((userID.equals(getID)) && (password.equals(getPassword))) {
                        getLogInUserID = getID;
                        getLogInPassword = getPassword;
                        new home().setVisible(true);
                        setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "INVALID USER_ID or PASSWORD !");
                        id.setText("");
                        pwd.setText("");
                        id.requestFocus();
                    }
                    con.close();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "INVALID USER_ID or PASSWORD !");
                    id.setText("");
                    pwd.setText("");
                    id.requestFocus();
                }

            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            id.requestFocus();
        }
    }//GEN-LAST:event_pwdKeyPressed

    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_ENTER) || (evt.getKeyCode() == KeyEvent.VK_DOWN)) {
            pwd.requestFocus();
        }
    }//GEN-LAST:event_idKeyPressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new forgetPassword().setVisible(true);
        setVisible(false);
        id.setText("");
        pwd.setText("");
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton logIn;
    private javax.swing.JPasswordField pwd;
    // End of variables declaration//GEN-END:variables

    String getLogInUserID() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
