
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class setting extends javax.swing.JFrame {

    /**
     * Creates new form setting
     */
    private int m = 0;

    public void createPassword() {
        //password verified and generate userID
        int max = 0;
        if (createPassword.getText().equals(confirmPassword.getText())) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "2507");
                Statement st = con.createStatement();
                String Query = "Select max(sn) from hospital_management_user;";
                ResultSet rs = st.executeQuery(Query);
                rs.next();
                max = Integer.parseInt(rs.getString("max(sn)"));
                max++;
                con.close();
            } catch (Exception e) {
            }
            System.out.println("" + max);
            m = max;
            String pre = "P01";
            String suf = "";

            if (max >= 10) {
                suf = "";
            } else if (max >= 0) {
                suf = "0";
            }
            getUserID.setText("" + pre + suf + max);
            JOptionPane.showMessageDialog(null, "USER ID has been created!\nRemember the USER_ID before click the CREATE ACCOUNT button.");
        } else {
            JOptionPane.showMessageDialog(null, "Uuupsss...\nConfirm Password is not same!");
            confirmPassword.setText("");
            confirmPassword.requestFocus();
        }
    }

    public String getUserID() {
        String r = "";
        logIn lg = new logIn();
        r = lg.getLogInUserID;

        return r;
    }

    public String getUserPassword() {
        String r = "";
        logIn lg = new logIn();
        r = lg.getLogInPassword;

        return r;
    }

    public void clear() {
        old_password.setText("");
        new_password01.setText("");
        new_password02.setText("");
    }

    public setting() {
        initComponents();
        old_password.requestFocus();
        create.setEnabled(false);
        
        home hm = new home();
        doc_name.setText(hm.name_);
        userCode_d.setText(hm.code_);
        userID.setText(hm.id_);
        age.setText("" + hm.age_);
        mob.setText(hm.mob_);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        doc_name = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        userCode_d = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        userID = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        mob = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        old_password = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        new_password01 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        new_password02 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        userCode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        createPassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        getUserID = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        confirmPassword = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(17, 16, 51));
        jPanel5.setToolTipText("");

        doc_name.setFont(new java.awt.Font("Verdana", 1, 26)); // NOI18N
        doc_name.setForeground(new java.awt.Color(255, 153, 153));
        doc_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doc_name.setText("DOCTOR NAME");
        doc_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("USER CODE : ");

        userCode_d.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        userCode_d.setForeground(new java.awt.Color(204, 255, 204));
        userCode_d.setText("0105SS22001");

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("USER ID : ");

        userID.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        userID.setForeground(new java.awt.Color(204, 255, 204));
        userID.setText("P0101");

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 255, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("AGE : ");

        age.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        age.setForeground(new java.awt.Color(204, 255, 204));
        age.setText("31");

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 255, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("MOBILE : ");

        mob.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        mob.setForeground(new java.awt.Color(204, 255, 204));
        mob.setText("9638527410");

        jLabel17.setBackground(new java.awt.Color(204, 255, 204));
        jLabel17.setFont(new java.awt.Font("Trajan Pro", 1, 28)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(24, 17, 45));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("PRASH HOSPITAL");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(doc_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userCode_d, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userID, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mob, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(doc_name)
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(userCode_d))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(userID))
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(age))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(mob))
                .addGap(133, 133, 133))
        );

        jTabbedPane1.addTab("", jPanel5);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        old_password.setBackground(new java.awt.Color(255, 255, 204));
        old_password.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        old_password.setForeground(new java.awt.Color(153, 0, 0));
        old_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        old_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                old_passwordKeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("CHANGE PASSWORD");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        new_password01.setBackground(new java.awt.Color(204, 255, 204));
        new_password01.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        new_password01.setForeground(new java.awt.Color(153, 0, 0));
        new_password01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        new_password01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                new_password01KeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("OLD PASSWORD");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("CONFIRM PASSWORD");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("NEW PASSWORD");

        new_password02.setBackground(new java.awt.Color(204, 255, 204));
        new_password02.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        new_password02.setForeground(new java.awt.Color(153, 0, 0));
        new_password02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        new_password02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_password02ActionPerformed(evt);
            }
        });
        new_password02.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                new_password02KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(new_password02)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_password01, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(old_password))
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(old_password, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(new_password01, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(new_password02, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        jTabbedPane1.addTab(" CHANGE PASSWORD ", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("ENTER USER CODE ");

        userCode.setBackground(new java.awt.Color(255, 204, 255));
        userCode.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        userCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        userCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCodeActionPerformed(evt);
            }
        });
        userCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userCodeKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("CREATE PAASSWORD");

        createPassword.setBackground(new java.awt.Color(204, 255, 204));
        createPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        createPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        createPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                createPasswordKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("CONFIRM PASSWORD");

        create.setBackground(new java.awt.Color(204, 255, 204));
        create.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        create.setForeground(new java.awt.Color(0, 0, 153));
        create.setText("CREATE ACCOUNT");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        getUserID.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        getUserID.setForeground(new java.awt.Color(255, 204, 204));
        getUserID.setText("*****");

        jButton3.setBackground(new java.awt.Color(255, 204, 255));
        jButton3.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 0));
        jButton3.setText("GET USER ID");
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 204));
        jLabel8.setText("YOUR USER ID : ");

        confirmPassword.setBackground(new java.awt.Color(204, 255, 204));
        confirmPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        confirmPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        confirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmPasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(getUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userCode)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createPassword)
                    .addComponent(confirmPassword)
                    .addComponent(create, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userCode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(getUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab(" ADD USER ", jPanel2);

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 204));
        jLabel10.setText("ENTER PASSWORD");

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("DELETE ACCOUNT");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        password.setBackground(new java.awt.Color(255, 204, 204));
        password.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        password.setForeground(new java.awt.Color(255, 0, 0));
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jLabel11)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(" DELETE USER ", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 236, 620, 560));

        jButton6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 0, 0));
        jButton6.setText("X");
        jButton6.setBorder(null);
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1870, 0, 50, 49));

        jPanel4.setBackground(new java.awt.Color(51, 0, 102));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("S E T T I N G");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(831, 831, 831)
                .addComponent(jLabel1)
                .addContainerGap(870, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1920, 80));

        jLabel9.setForeground(new java.awt.Color(204, 255, 204));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settingBG.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id = getUserID();
        String password = "";
        String current = old_password.getText();
        String newPassword = new_password01.getText();
        String confirmPassword = new_password02.getText();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "2507");
            Statement st = con.createStatement();
            String Query = " select * from hospital_management_user where userID = '" + id + "';";
            ResultSet rs = st.executeQuery(Query);
            rs.next();
            password = rs.getString("password");
            if (password.equals(current)) {
                if (newPassword.equals(confirmPassword)) {
                    if (!password.equals(newPassword)) {
                        String QueryUpdate = "update hospital_management_user set password = '" + newPassword + "' where userID = '" + id + "';";
                        st.executeUpdate(QueryUpdate);
                        con.close();
                        JOptionPane.showMessageDialog(null, "Password changed successfully..!");
                        new logIn().setVisible(true);
                        setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Your current and new password are same!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Your new and confirm password are not same!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Something got WRONG !\nWRONG CURRENT PASSWORD * * *");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        clear();
        old_password.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Do you want to back?", "* * * A L E R T * * *", JOptionPane.YES_NO_OPTION) == 0) {
            clear();
            new home().setVisible(true);
            setVisible(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void old_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_old_passwordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            new_password01.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            new_password02.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            new_password01.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_old_passwordKeyPressed

    private void new_password01KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_password01KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            new_password02.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            old_password.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            new_password02.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_new_password01KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!userCode.getText().trim().isEmpty()) {
            //verify User Code
            String user_Code = userCode.getText();
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "2507");
                Statement st = con.createStatement();
                String Query = "select * from hospital_management_user_code where userCode = '" + user_Code + "';";
                ResultSet rs = st.executeQuery(Query);
                rs.next();
                String orCode = rs.getString("userCode");

                if (orCode.equals(user_Code)) {
                    String account = rs.getString("account");
                    System.out.println(account);
                    if (!account.equals("yes")) {
                        if (createPassword.getText().isEmpty()) {
                            JOptionPane.showMessageDialog(null, "Uppsss...\nEnter a VALID password!");
                        } else {
                            createPassword();
                            userCode.setEnabled(false);
                            createPassword.setEnabled(false);
                            confirmPassword.setEnabled(false);
                            create.setEnabled(true);
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "You have already an ACCOUNT.!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "INVALID USER CODE");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Please enter VALID USER_CODE");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please enter VALID USER_CODE");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        String id = getUserID.getText();
        String pwd = createPassword.getText();
        String code = userCode.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "2507");
            Statement st = con.createStatement();
            String Query = "insert into hospital_management_user values(" + m + ", '" + id + "', '" + pwd + "', '" + code + "');";
            st.executeUpdate(Query);
            Query = "update hospital_management_user_code set account = 'yes' where userCode = '" + code + "';";
            st.executeUpdate(Query);
            JOptionPane.showMessageDialog(null, "ACCOUNT CREATED SUCCESSFULLY!");
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        create.setEnabled(false);
        userCode.setEnabled(true);
        createPassword.setEnabled(true);
        confirmPassword.setEnabled(true);
        userCode.setText("");
        createPassword.setText("");
        confirmPassword.setText("");
        getUserID.setText("*****");
        userCode.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_createActionPerformed

    private void userCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userCodeKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) {
            createPassword.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            confirmPassword.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_userCodeKeyPressed

    private void userCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userCodeActionPerformed

    private void createPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createPasswordKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) {
            confirmPassword.requestFocus();
        } else if ((evt.getKeyCode() == KeyEvent.VK_UP)) {
            userCode.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_createPasswordKeyPressed

    private void new_password02KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_password02KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            old_password.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            new_password01.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String id = getUserID();
            String password = "";
            String current = old_password.getText();
            String newPassword = new_password01.getText();
            String confirmPassword = new_password02.getText();

            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "2507");
                Statement st = con.createStatement();
                String Query = " select * from hospital_management_user where userID = '" + id + "';";
                ResultSet rs = st.executeQuery(Query);
                rs.next();
                password = rs.getString("password");
                if (password.equals(current)) {
                    if (newPassword.equals(confirmPassword)) {
                        if (!password.equals(newPassword)) {
                            String QueryUpdate = "update hospital_management_user set password = '" + newPassword + "' where userID = '" + id + "';";
                            st.executeUpdate(QueryUpdate);
                            con.close();
                            JOptionPane.showMessageDialog(null, "Password changed successfully..!");
                            new logIn().setVisible(true);
                            setVisible(false);
                        } else {
                            JOptionPane.showMessageDialog(null, "Your current and new password are same!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Your new and confirm password are not same!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Something got WRONG !\nWRONG CURRENT PASSWORD * * *");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            clear();
            old_password.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_new_password02KeyPressed

    private void new_password02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_password02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_password02ActionPerformed

    private void confirmPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            userCode.requestFocus();
        } else if ((evt.getKeyCode() == KeyEvent.VK_UP)) {
            createPassword.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!userCode.getText().trim().isEmpty()) {
                //verify User Code
                String user_Code = userCode.getText();
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "2507");
                    Statement st = con.createStatement();
                    String Query = "select * from hospital_management_user_code where userCode = '" + user_Code + "';";
                    ResultSet rs = st.executeQuery(Query);
                    rs.next();
                    String orCode = rs.getString("userCode");

                    if (orCode.equals(user_Code)) {
                        String account = rs.getString("account");

                        if (!account.equals("yes")) {

                            if (createPassword.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null, "Uppsss\nEnter a VALID password!");
                            } else {
                                createPassword();
                                userCode.setEnabled(false);
                                createPassword.setEnabled(false);
                                confirmPassword.setEnabled(false);
                                create.setEnabled(true);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "You have already an ACCOUNT.!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "INVALID USER CODE");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Please enter VALID USER_CODE");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Please enter VALID USER_CODE");
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String userCode = "";
        String id = getUserID();
        String pwd = getUserPassword();
        if (pwd.equals(password.getText())) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "2507");
                Statement st = con.createStatement();
                String Query = "select * from hospital_management_user where userID ='" + id + "';";
                ResultSet rs = st.executeQuery(Query);
                rs.next();
                userCode = rs.getString("userCode");
                if (JOptionPane.showConfirmDialog(null, "Do you want to delete account?\nUSER_CODE = " + userCode + "\nUSER_ID = " + id + "\nPASSWORD = " + pwd + "", "* * * A L E R T * * *", JOptionPane.YES_NO_OPTION) == 0) {
                    Query = "delete from hospital_management_user where userCode = '" + userCode + "';";
                    st.executeUpdate(Query);

                    Query = "update hospital_management_user_code set account = '' where userCode = '" + userCode + "';";
                    st.executeUpdate(Query);

                    JOptionPane.showMessageDialog(null, "ACCOUNT DELETED SUCCESSFULLY!");
                    new logIn().setVisible(true);
                    setVisible(false);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        } else {
            JOptionPane.showMessageDialog(null, "WRONG PASSWORD!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String userCode = "";
            String id = getUserID();
            String pwd = getUserPassword();
            if (pwd.equals(password.getText())) {
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "2507");
                    Statement st = con.createStatement();
                    String Query = "select * from hospital_management_user where userID ='" + id + "';";
                    ResultSet rs = st.executeQuery(Query);
                    rs.next();
                    userCode = rs.getString("userCode");
                    if (JOptionPane.showConfirmDialog(null, "Do you want to delete account?\nUSER_CODE = " + userCode + "\nUSER_ID = " + id + "\nPASSWORD = " + pwd + "", "* * * A L E R T * * *", JOptionPane.YES_NO_OPTION) == 0) {
                        Query = "delete from hospital_management_user where userCode = '" + userCode + "';";
                        st.executeUpdate(Query);

                        Query = "update hospital_management_user_code set account = '' where userCode = '" + userCode + "';";
                        st.executeUpdate(Query);

                        JOptionPane.showMessageDialog(null, "ACCOUNT DELETED SUCCESSFULLY!");
                        new logIn().setVisible(true);
                        setVisible(false);
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

            } else {
                JOptionPane.showMessageDialog(null, "WRONG PASSWORD!");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JButton create;
    private javax.swing.JTextField createPassword;
    private javax.swing.JLabel doc_name;
    private javax.swing.JLabel getUserID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mob;
    private javax.swing.JTextField new_password01;
    private javax.swing.JPasswordField new_password02;
    private javax.swing.JTextField old_password;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField userCode;
    private javax.swing.JLabel userCode_d;
    private javax.swing.JLabel userID;
    // End of variables declaration//GEN-END:variables
}
